### ISSUE TITLE
Sunpath and Wind speed as data input

### ISSUE THREAD

**Issue by seamoo** [ladybug-tools/ladybug-blender#18]
Seeing an issue when use wind speed as the data input on the sun path
1) The suns are all the same colour and do not reflect the colour range on the legend
2) When I use the projections option on the sunpath node the suns and data colour coding do not show up

![sunpathwithwindspeed](https://user-images.githubusercontent.com/25322402/95201657-da912e00-07fd-11eb-88a9-0e460c43a83e.JPG)

Weathefile used: https://www.energyplus.net/weather-download/asia_wmo_region_2/IND//IND_Mumbai.430030_IWEC/all

**Comment by mostaphaRoudsari** [comment]
Hi @seamoo, this is most likely because of the input data. The average wind speed is around 2.0 but there are a number of hours with windspeed as high as 27. If you set the max to 6 or so you should be able to see the variety of the data.

![image](https://user-images.githubusercontent.com/2915573/95208140-b827f200-07b6-11eb-87d2-892c2920230d.png)

**Comment by seamoo** [comment]
> Hi @seamoo, this is most likely because of the input data. The average wind speed is around 2.0 but there are a number of hours with windspeed as high as 27. If you set the max to 6 or so you should be able to see the variety of the data.
> 
> ![image](https://user-images.githubusercontent.com/2915573/95208140-b827f200-07b6-11eb-87d2-892c2920230d.png)

Hi @mostaphaRoudsari . Setting to max of 6 worked. It now color coded. 

**Note**: The projections when set are not displaying suns or colours.

![lbsunprojection](https://user-images.githubusercontent.com/25322402/95209006-78d5c180-0807-11eb-8144-8dc2274c42b3.JPG)

**Comment by mostaphaRoudsari** [comment]
> Note: The projections when set are not displaying suns or colours.

Forgot about that one. That one is for @Moult to figure out. 😀 Not sure what is going on.

**Comment by Moult** [comment]
I seem to have missed support for 2D points :) All fixed now! Thanks so much for the report!

**Comment by seamoo** [comment]
Hi @Moult I've installed the new patched version you shared. I get the following error when setting either the Stereographic or Orthographic projections. 

Traceback (most recent call last):
  File "C:\Users\smooney\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\ladybug_tools\nodes\ladybug\LB_Out.py", line 31, in execute
    def execute(self, context):
  File "C:\Users\smooney\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\ladybug_tools\nodes\ladybug\LB_Out.py", line 57, in refresh
    
  File "C:\Users\smooney\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\ladybug_tools\nodes\ladybug\LB_Out.py", line 78, in process
    for geometry in geometries:
  File "C:\Users\smooney\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\ladybug_tools\nodes\ladybug\LB_Out.py", line 300, in create_blender_colored_v
    data.align_y = 'TOP'
  File "C:\Users\smooney\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\ladybug_tools\nodes\ladybug\LB_Out.py", line 300, in <listcomp>
    data.align_y = 'TOP'
AttributeError: 'Point2D' object has no attribute 'z'

location: <unknown location>:-1

**Comment by Moult** [comment]
@seamoo the trace doesn't seem to make sense. I see you're online on IRC, send me a message and we can organise a quick screenshare to help debug

**Comment by Moult** [comment]
So, uh, I assume this is fixed?

**Comment by seamoo** [comment]
> So, uh, I assume this is fixed?
@Moult. Unfortunatly not. It's bugging out whenever I connect a EPW file. The error text is below. As an experiment I changed the weather file, same error. I have rebuilt the nodes is a new file as a test, the error remains. 

Traceback (most recent call last):
  File "C:\Users\smooney\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\ladybug_tools\nodes\ladybug\LB_Out.py", line 33, in execute
    node.refresh()
  File "C:\Users\smooney\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\ladybug_tools\nodes\ladybug\LB_Out.py", line 60, in refresh
    self.process()
  File "C:\Users\smooney\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\ladybug_tools\nodes\ladybug\LB_Out.py", line 77, in process
    for geometries in socket.sv_get():
  File "C:\Users\smooney\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\sverchok-master\core\sockets.py", line 125, in sv_get
    return self.convert_data(SvGetSocket(self, deepcopy), implicit_conversions)
  File "C:\Users\smooney\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\sverchok-master\core\socket_data.py", line 121, in SvGetSocket
    raise SvNoDataError(socket, msg="not found in socket_data_cache")
sverchok.core.socket_data.SvNoDataError: node LB Out (socket geometry) not found in socket_data_cache

location: <unknown location>:-1



![epw](https://user-images.githubusercontent.com/25322402/95326730-a763a300-08c0-11eb-8709-286faff1a9f4.JPG)

**Comment by Moult** [comment]
Reopening bug until this gets resolved.

That error message looks a little late. It is an error at the LB Out node, whereas the actual error occurs sooner. Can you open up the console and check if there are any other messages? Otherwise, catch me online tomorrow on IRC and we can screenshare to debug.

**Comment by mostaphaRoudsari** [comment]
> AttributeError: 'Point2D' object has no attribute 'z'

Could it be that in your conversion for visualizing the sunpath you are treating Point2D and Point3D the same on the Blender side and it is looking for the `z` attribute which is invalid for Point2D? We can probably catch this exception and set the `z` value to the `z` value for the center of the sunpath if there is no concept of Point2D in Blender.

**Comment by Moult** [comment]
@mostaphaRoudsari we had a screenshare and that error was due to an unclean upgrade (I manually sent him a new build to try out the fix) - the stack trace had a mix of old and new code that didn't make sense. Hopefully we'll get the chance to screenshare again today.

**Comment by Moult** [comment]
Closing as an upgrade to the latest master branch version has fixed these issues over the screenshare.
